### ISSUE TITLE
Add functionality to infer information from a PDS3/PDS4 table

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-pdstemplate#8]
Per recent discussions about oops and metadata generation, add the following features to `PdsTemplate`:

- A function that takes a PDS3/PDS4 table as an argument, reads the table, and infers the starting bytes, column width, and data types for each column.
- A function that returns the number of columns founds.
- A function that, given a column number, returns the column starting byte.
- A function that, given a column number, returns the column width.
- A function that, given a column number, returns the column data type (in PDS3 format).
- A function that, given a column number, returns the column data type (in PDS4 format).

**Comment by rfrenchseti** [comment]
Fixed by #10

**Comment by jnspitale** [comment]
Does the new pdstemplate merge satisfy this issue?

**Comment by rfrenchseti** [comment]
Yes - this issue was already closed.
